---
- name: Get list of the instances
  ec2_instance_info:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_region_final | default(aws_region) | default(region) | default('us-east-1')}}"
  register: ec2_instances

- name: Stop VM instances
  ec2_instance:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_region_final | default(aws_region) | default(region) | default('us-east-1')}}"
    state: stopped
    instance_ids: ["{{ instance.instance_id }}"]
  loop: "{{ ec2_instances.instances}}"
  loop_control:
    loop_var: instance
