- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  tags:
  - step001
  - pre_infrastructure
  tasks:
  - debug: var=purpose

  - name: Find AMI id for test/release/production
    import_role:
      name: infra-ec2-custom-images
    vars:
      ACTION: "find"
    when: purpose == "test" or purpose == "release" or purpose == "production"
