- name: Test website access
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure website is accessible
      uri:
        url: "http://workstation.{{ subdomain_base }}"
        method: GET
      register: _result
      until: _result.status == 200
      retries: 12 # 12 * 10 seconds = 2 minutes
      delay: 10 # Every 10 seconds
