---
ec2_copy_vm_disk_to_image_task: false
ec2_copy_vm_disk_to_image_list: []
ec2_copy_volume_to_image_task: false
ec2_copy_volume_to_image_list: []
ec2_custom_images: []
ec2_release_images_zones: [] 
ec2_release_image_version: ""
